logging:
  level:
    org.springframework.web.client.RestClient: DEBUG

marvel:
  url: https://gateway.marvel.com/v1/public
  public-key: ${PUBLIC_KEY}
  private-key: ${PRIVATE_KEY}

spring:
  datasource:
    embedded-database-connection: h2
    url: jdbc:h2:mem:audit;INIT=RUNSCRIPT FROM 'h2init.sql';
    username: sa
    password: admin
  h2:
    console.enabled: true

server.servlet.context-path: /v1